import type { PlatformPlan } from '../types/plans';

export const INITIAL_CANONICAL_PLANS: PlatformPlan[] = [
  {
    id: 'plan-standard-seed',
    key: 'standard',
    name: 'Plan Estándar',
    description: 'Solución esencial para comercios y profesionales independientes que inician su digitalización.',
    status: 'active',
    displayOrder: 1,
    isPopular: false,
    isActive: true,
    version: 1,
    trialDays: 14,
    gracePeriodDays: 14,
    credits: {
      monthly: 10000,
      rollover: false,
    },
    limits: {
      maxUsers: 3,
      maxBranches: 1,
      storageGb: 5,
      apiRateLimit: 60,
    },
    discount: {
      enabled: true,
      percentage: 17,
      durationMonths: 12,
    },
    prices: [
      {
        currency: 'ARS',
        amount: 29900,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 29,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'ARS',
        amount: 80900,
        interval: 'quarterly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 80,
        interval: 'quarterly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 290,
        interval: 'yearly',
        isActive: true,
      },
    ],
    includedFeatures: [
      'services.bookings',
      'services.bookings.create',
      'services.bookings.reschedule',
      'commerce.catalog',
      'commerce.orders',
    ],
    createdAt: '2026-04-10T12:00:00.000Z',
    updatedAt: '2026-05-15T10:30:00.000Z',
  },
  {
    id: 'plan-pro-seed',
    key: 'pro',
    name: 'Plan Profesional',
    description: 'Para empresas en expansión que requieren automatización, carga de adjuntos y fidelización de clientes.',
    status: 'active',
    displayOrder: 2,
    isPopular: true,
    isActive: true,
    version: 2,
    trialDays: 14,
    gracePeriodDays: 14,
    credits: {
      monthly: 50000,
      rollover: true,
    },
    limits: {
      maxUsers: 15,
      maxBranches: 3,
      storageGb: 25,
      apiRateLimit: 300,
    },
    discount: {
      enabled: true,
      percentage: 17,
      durationMonths: 12,
    },
    prices: [
      {
        currency: 'ARS',
        amount: 59900,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 59,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'ARS',
        amount: 161900,
        interval: 'quarterly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 160,
        interval: 'quarterly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 590,
        interval: 'yearly',
        isActive: true,
      },
    ],
    includedFeatures: [
      'services.bookings',
      'services.bookings.create',
      'services.bookings.reschedule',
      'services.bookings.photo_upload',
      'commerce.catalog',
      'commerce.orders',
      'commerce.orders.dispatch',
      'crm.customers',
      'marketing.campaigns',
    ],
    createdAt: '2026-04-12T14:00:00.000Z',
    updatedAt: '2026-05-21T18:45:00.000Z',
  },
  {
    id: 'plan-enterprise-seed',
    key: 'enterprise',
    name: 'Plan Corporativo',
    description: 'Infraestructura de alta disponibilidad, integración por API y soporte prioritario para grandes franquicias.',
    status: 'active',
    displayOrder: 3,
    isPopular: false,
    isActive: true,
    version: 3,
    trialDays: 30,
    gracePeriodDays: 30,
    credits: {
      monthly: 150000,
      rollover: true,
    },
    limits: {
      maxUsers: 100,
      maxBranches: 20,
      storageGb: 200,
      apiRateLimit: 1200,
    },
    discount: {
      enabled: true,
      percentage: 17,
      durationMonths: 12,
    },
    prices: [
      {
        currency: 'ARS',
        amount: 149900,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 149,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'ARS',
        amount: 404900,
        interval: 'quarterly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 405,
        interval: 'quarterly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 1490,
        interval: 'yearly',
        isActive: true,
      },
    ],
    includedFeatures: [
      'services.bookings',
      'services.bookings.create',
      'services.bookings.reschedule',
      'services.bookings.photo_upload',
      'commerce.catalog',
      'commerce.orders',
      'commerce.orders.dispatch',
      'crm.customers',
      'marketing.campaigns',
      'gastronomy.tables',
      'gastronomy.kitchen',
      'core.audit',
    ],
    createdAt: '2026-04-15T09:00:00.000Z',
    updatedAt: '2026-06-01T16:20:00.000Z',
  },
  {
    id: 'plan-custom-seed',
    key: 'custom',
    name: 'Plan Personalizado',
    description: 'Solución a medida y cotización personalizada para organizaciones con requerimientos de alta escala, integraciones dedicadas o SLA exclusivo.',
    status: 'active',
    displayOrder: 4,
    isPopular: false,
    isCustom: true,
    isActive: true,
    version: 1,
    trialDays: 30,
    gracePeriodDays: 30,
    credits: {
      monthly: 500000,
      rollover: true,
    },
    limits: {
      maxUsers: 250,
      maxBranches: 50,
      storageGb: 1000,
      apiRateLimit: 5000,
    },
    prices: [],
    includedFeatures: [
      'services.bookings',
      'services.bookings.create',
      'services.bookings.reschedule',
      'services.bookings.photo_upload',
      'commerce.catalog',
      'commerce.orders',
      'commerce.orders.dispatch',
      'crm.customers',
      'marketing.campaigns',
      'gastronomy.tables',
      'gastronomy.kitchen',
      'core.audit',
    ],
    createdAt: '2026-04-18T10:00:00.000Z',
    updatedAt: '2026-06-05T12:00:00.000Z',
  },
  {
    id: 'plan-starter-draft-seed',
    key: 'starter-promo',
    name: 'Plan Starter Promocional',
    description: 'Borrador de plan promocional para campañas estacionales y primeros comercios afiliados.',
    status: 'draft',
    displayOrder: 5,
    isPopular: false,
    isActive: false,
    version: 1,
    trialDays: 7,
    gracePeriodDays: 7,
    credits: {
      monthly: 5000,
      rollover: false,
    },
    limits: {
      maxUsers: 1,
      maxBranches: 1,
      storageGb: 2,
      apiRateLimit: 30,
    },
    prices: [
      {
        currency: 'ARS',
        amount: 14900,
        interval: 'monthly',
        isActive: true,
      },
      {
        currency: 'USD',
        amount: 15,
        interval: 'monthly',
        isActive: true,
      },
    ],
    includedFeatures: [
      'services.bookings',
      'commerce.catalog',
    ],
    createdAt: '2026-08-01T11:00:00.000Z',
    updatedAt: '2026-08-01T11:00:00.000Z',
  },
];
