import type { ModuleCatalogEntry } from '../types/modules';

export interface SectionMeta {
  key: string;
  name: string;
  description: string;
  icon: string;
}

export const CANONICAL_SECTIONS: Record<string, SectionMeta> = {
  services: {
    key: 'services',
    name: 'Servicios',
    description: 'Prestación de servicios profesionales por turno (peluquería, salud, estética, estudios).',
    icon: 'calendar',
  },
  commerce: {
    key: 'commerce',
    name: 'Comercio',
    description: 'Transacciones comerciales, catálogo, inventario, ventas y caja.',
    icon: 'shopping-cart',
  },
  gastronomy: {
    key: 'gastronomy',
    name: 'Gastronomía',
    description: 'Operación de salón, mesas físicas y pantalla de cocina (KDS).',
    icon: 'utensils',
  },
  crm: {
    key: 'crm',
    name: 'Gestión de Clientes',
    description: 'Directorio de clientes, historial de visitas y preferencias.',
    icon: 'users',
  },
  marketing: {
    key: 'marketing',
    name: 'Marketing y Promociones',
    description: 'Programas de fidelización y cupones de descuento.',
    icon: 'tag',
  },
  core: {
    key: 'core',
    name: 'Administración Core',
    description: 'Administración de la cuenta, branding, equipo y suscripción.',
    icon: 'settings',
  },
};

export const INITIAL_CANONICAL_ENTRIES: ModuleCatalogEntry[] = [
  // Services -> Bookings
  {
    id: 'seed-services-bookings',
    key: 'services.bookings',
    kind: 'module',
    moduleKey: 'bookings',
    sectionKey: 'services',
    pageKey: 'bookings',
    scope: 'tenant',
    name: 'Agenda de Turnos y Citas',
    description: 'Gestión integral de turnos, profesionales y disponibilidad horaria.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: [],
    requiredPermissions: ['bookings:read'],
    availability: { plans: ['Básico', 'Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'services-team',
    manifest: 'src/tenant/sections/services/bookings',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-services-bookings-create',
    key: 'services.bookings.create',
    kind: 'feature',
    moduleKey: 'bookings',
    sectionKey: 'services',
    pageKey: 'bookings',
    scope: 'tenant',
    name: 'Crear reservas',
    description: 'Permite agendar turnos y citas online desde la web y el panel de administración.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['services.bookings'],
    requiredPermissions: ['bookings:write'],
    availability: { plans: ['Básico', 'Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'services-team',
    manifest: 'src/tenant/sections/services/bookings/create',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-services-bookings-photo-upload',
    key: 'services.bookings.photo_upload',
    kind: 'feature',
    moduleKey: 'bookings',
    sectionKey: 'services',
    pageKey: 'bookings',
    scope: 'tenant',
    name: 'Subir foto a la reserva',
    description: 'Permite adjuntar imágenes de referencia al agendar servicios estéticos o diagnósticos.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['services.bookings', 'services.bookings.create'],
    requiredPermissions: ['bookings:write'],
    availability: { plans: ['Plan Pro'], requiresSubscription: true },
    ownerTeam: 'services-team',
    manifest: 'src/tenant/sections/services/bookings/photo_upload',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-services-bookings-reschedule',
    key: 'services.bookings.reschedule',
    kind: 'feature',
    moduleKey: 'bookings',
    sectionKey: 'services',
    pageKey: 'bookings',
    scope: 'tenant',
    name: 'Reprogramar turno',
    description: 'Permite modificar fecha, hora y operador de una cita existente con notificación al cliente.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['services.bookings'],
    requiredPermissions: ['bookings:write'],
    availability: { plans: ['Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'services-team',
    manifest: 'src/tenant/sections/services/bookings/reschedule',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-services-bookings-notifications',
    key: 'services.bookings.notifications',
    kind: 'feature',
    moduleKey: 'bookings',
    sectionKey: 'services',
    pageKey: 'bookings',
    scope: 'tenant',
    name: 'Recordatorios automáticos',
    description: 'Envío automático de notificaciones por WhatsApp/Email antes de cada cita agendada.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['services.bookings'],
    requiredPermissions: ['bookings:read'],
    availability: { plans: ['Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'services-team',
    manifest: 'src/tenant/sections/services/bookings/notifications',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Commerce -> Catalog
  {
    id: 'seed-commerce-catalog',
    key: 'commerce.catalog',
    kind: 'module',
    moduleKey: 'catalog',
    sectionKey: 'commerce',
    pageKey: 'catalog',
    scope: 'tenant',
    name: 'Catálogo de Productos y Servicios',
    description: 'Gestión de artículos, variantes, precios y categorías comerciales.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: [],
    requiredPermissions: ['catalog:read'],
    availability: { plans: ['Básico', 'Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'commerce-team',
    manifest: 'src/tenant/sections/commerce/catalog',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-commerce-catalog-items',
    key: 'commerce.catalog.items',
    kind: 'feature',
    moduleKey: 'catalog',
    sectionKey: 'commerce',
    pageKey: 'catalog',
    scope: 'tenant',
    name: 'Artículos y Categorías',
    description: 'Creación y edición de fichas de productos y servicios con precios.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['commerce.catalog'],
    requiredPermissions: ['catalog:write'],
    availability: { plans: ['Básico', 'Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'commerce-team',
    manifest: 'src/tenant/sections/commerce/catalog/items',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-commerce-catalog-add-to-cart',
    key: 'commerce.catalog.add_to_cart',
    kind: 'feature',
    moduleKey: 'catalog',
    sectionKey: 'commerce',
    pageKey: 'catalog',
    scope: 'tenant',
    name: 'Carrito de Compras',
    description: 'Permite a los usuarios seleccionar artículos y armar un pedido online.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['commerce.catalog'],
    requiredPermissions: ['catalog:read'],
    availability: { plans: ['Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'commerce-team',
    manifest: 'src/tenant/sections/commerce/catalog/add_to_cart',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Commerce -> Orders
  {
    id: 'seed-commerce-orders',
    key: 'commerce.orders',
    kind: 'module',
    moduleKey: 'orders',
    sectionKey: 'commerce',
    pageKey: 'orders',
    scope: 'tenant',
    name: 'Ventas y Pedidos Multicanal',
    description: 'Gestión centralizada de transacciones de compraventa, mostrador, delivery y salón.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['commerce.catalog'],
    requiredPermissions: ['orders:read'],
    availability: { plans: ['Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'commerce-team',
    manifest: 'src/tenant/sections/commerce/orders',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-commerce-orders-split-bill',
    key: 'commerce.orders.split_bill',
    kind: 'feature',
    moduleKey: 'orders',
    sectionKey: 'commerce',
    pageKey: 'orders',
    scope: 'tenant',
    name: 'División de Cuenta (Split Bill)',
    description: 'Permite pagar una comanda o pedido fraccionando montos por comensal o medio de pago.',
    status: 'draft',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['commerce.orders'],
    requiredPermissions: ['orders:write'],
    availability: { plans: ['Plan Pro'], requiresSubscription: true },
    ownerTeam: 'commerce-team',
    manifest: 'src/tenant/sections/commerce/orders/split_bill',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Gastronomy -> Tables
  {
    id: 'seed-gastronomy-tables',
    key: 'gastronomy.tables',
    kind: 'module',
    moduleKey: 'tables',
    sectionKey: 'gastronomy',
    pageKey: 'tables',
    scope: 'tenant',
    name: 'Salón y Mesas Físicas',
    description: 'Mapa de distribución de mesas, estado de ocupación y comandas en salón.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['commerce.orders'],
    requiredPermissions: ['tables:read'],
    availability: { plans: ['Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'gastronomy-team',
    manifest: 'src/tenant/sections/gastronomy/tables',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-gastronomy-tables-qr',
    key: 'gastronomy.tables.qr_generator',
    kind: 'feature',
    moduleKey: 'tables',
    sectionKey: 'gastronomy',
    pageKey: 'tables',
    scope: 'tenant',
    name: 'Generador de QR por Mesa',
    description: 'Genera códigos QR dinámicos para que los comensales accedan al menú digital.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: ['gastronomy.tables'],
    requiredPermissions: ['tables:write'],
    availability: { plans: ['Estándar', 'Plan Pro'], requiresSubscription: true },
    ownerTeam: 'gastronomy-team',
    manifest: 'src/tenant/sections/gastronomy/tables/qr_generator',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-gastronomy-tables-bookings',
    key: 'gastronomy.tables.bookings',
    kind: 'feature',
    moduleKey: 'tables',
    sectionKey: 'gastronomy',
    pageKey: 'tables',
    scope: 'tenant',
    name: 'Reservas de Mesa en Salón',
    description: 'Asignación de mesas gastronómicas por anticipado (aislado de services.bookings).',
    status: 'toBeDeprecated',
    isArchived: false,
    maintenanceEnabled: true,
    maintenanceMessage: 'Migrando a nuevo motor de asignación de zonas.',
    version: 2,
    dependencies: ['gastronomy.tables'],
    requiredPermissions: ['tables:write'],
    availability: { plans: ['Plan Pro'], requiresSubscription: true },
    ownerTeam: 'gastronomy-team',
    manifest: 'src/tenant/sections/gastronomy/tables/bookings',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // CRM -> Clients
  {
    id: 'seed-crm-clients',
    key: 'crm.clients',
    kind: 'module',
    moduleKey: 'clients',
    sectionKey: 'crm',
    pageKey: 'clients',
    scope: 'tenant',
    name: 'Fichas y Directorio de Clientes',
    description: 'Historial de compras, reservas, preferencias y datos de contacto de clientes.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: [],
    requiredPermissions: ['clients:read'],
    availability: { plans: ['Básico', 'Estándar', 'Plan Pro'], requiresSubscription: false },
    ownerTeam: 'crm-team',
    manifest: 'src/tenant/sections/crm/clients',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Core -> Theme
  {
    id: 'seed-core-theme',
    key: 'core.theme',
    kind: 'module',
    moduleKey: 'theme',
    sectionKey: 'core',
    pageKey: 'theme',
    scope: 'platform',
    name: 'Branding y Theme Engine',
    description: 'Personalización de paleta de colores, tipografía, logos y tokens CSS dinámicos.',
    status: 'active',
    isArchived: false,
    maintenanceEnabled: false,
    version: 1,
    dependencies: [],
    requiredPermissions: ['theme:read', 'theme:write'],
    availability: { plans: ['Básico', 'Estándar', 'Plan Pro'], requiresSubscription: false },
    ownerTeam: 'core-team',
    manifest: 'src/tenant/sections/core/theme',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
